# Generated by Django 5.2.3 on 2026-04-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='ward',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
